CREATE TABLE IF NOT EXISTS users (
	id	      VARCHAR(36) PRIMARY KEY,
	email 	      VARCHAR(255) UNIQUE NOT NULL,
	password_hash BLOB NOT NULL,
	role 	      TINYINT NOT NULL DEFAULT 1 -- 0:ADMIN, 1:GUEST
);

CREATE TABLE IF NOT EXISTS lists (
	id	    VARCHAR(36) PRIMARY KEY,
	owner_id    VARCHAR(36) NOT NULL,
	title	    VARCHAR(255) NOT NULL,
	description TEXT,
	FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tasks (
	id	     VARCHAR(36) PRIMARY KEY,
	list_id      VARCHAR(36) NOT NULL,
	title	     VARCHAR(255) NOT NULL,
	description  TEXT,
	is_completed BOOLEAN DEFAULT FALSE,
	deadline     TIMESTAMP NULL,
	created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at   TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (list_id) REFERENCES lists(id) ON DELETE CASCADE
);
